### ISSUE TITLE
Changing views on custom moons

### ISSUE THREAD

**Issue by Hash3213** [sfDesat/Celestial-Tint#8]
Thank you for your marvelous mod. It is very cinematic!)

I have some custom planets. Two of them are coved with water so i need tag "ocean' for them but they are seen as default "Wasteland" from the ship.

It is said: "To change the planet preview that is seen from orbit, simply open your ExtendedLevel and change the first tag under LevelTags to the desired tag". Where can I find "ExtendedLevel" file and "LevelTags"? Is it in .dll files "NightSky" or/and "DynamiCulling" or somewhere in BepInEx/configs?

**Comment by sfDesat** [comment]
The way the LevelTag system works, means only the moon developers can change the tags. This will not (at least for now) be a config option. If you are a moon developer and use LethalLevelLoader, there is an option for LevelTags in the bottom of the ExtendedLevel

**Comment by Hash3213** [comment]
Ok. Unfortunately, I am not a moon developer. The thing is - i just wanted to make gameplay with friends more beautiful. This willing was so big that i even managed to turn Nightsky.dll into code and started to understand CSharp). (Yea, i soon found out your open code, but it was late =) ). I think, that i came very close when i found  Nightskymanager and lines: ''ightSkyManager.LoadAndSetPrefab(selectableLevel, "Prefab_Wasteland"'. Can you still give advise how at least change default Prefab Wasteland on for expl Ocean for planets without tags? It is said, that without tags mod will choose among 3 basic prefabs, but i think it chooses only one, default - wasteland.

**Comment by sfDesat** [comment]
![image](https://github.com/sfDesat/Celestial-Tint/assets/75356901/9db6c95d-1461-436d-aade-2c9b484774ba)
In the base game there are three different planetpreviews Moon1 (used by Experimentation, assurance and offense and i think the company?), Moon2 (used by Vow, March) and Moon3 (used by Rend, Dine and Titan). I replace them with a prefab i made that comes close to it. The problem is that most moon developers just leave it as Moon1 (which is Wasteland). I introduces the LevelTags thing to increase the amount of options developers have when choosing planetpreviews. If you want you can change which prefab gets applied to which tag, but this will probably not fix your issue. I think the only fix for that is to change the tag in the ExtendedLevel asset (which can only be accessed by the moon developer, because it is inside the unity engine).
![image](https://github.com/sfDesat/Celestial-Tint/assets/75356901/064f9823-ac34-4d62-ac5d-5ea886d4836f)
*All the tags and their respective prefabs ^*
If you are advanced in coding, you could try adding something to the code that would also check for SelectableLevel names and then assigning Prefabs to them.   
Sourcecode is here https://github.com/sfDesat/Celestial-Tint/tree/main/Sourcecode and the NightSkyManager is what you are looking for.

**Comment by Hash3213** [comment]
I believe now I have to get additional information about Csharp coding and then to follow you recommendations. The unity engine i suppose works on CSharp too (anyway it works either on CSharp or Java) but getting into engine is rather complicated. The Company building uses third Prefab - "Snow". Thanks for feedback anyway, you've answered on question and even helped with another issue.

**Comment by sfDesat** [comment]
I have made some changes in v1.2.0. I renamed [some files](https://github.com/sfDesat/Celestial-Tint/blob/main/Sourcecode/CelestialTintLoader.cs) and changes code on Line 79-91. I also updated the prefab list
