### ISSUE TITLE
Changing LethalLevelLoader version

### ISSUE THREAD

**Issue by LinkTroisUn** [sfDesat/Celestial-Tint#9]
LethalLevelLoader has not been updated for a few months, and because of that, it makes it hardly compatible with v50. Maybe you could try to use this [version](https://thunderstore.io/c/lethal-company/p/Pineguys/LethalLevelLoaderFixedV50/) or this [one](https://thunderstore.io/c/lethal-company/p/Refract/LethalLevelLoaderFixed/) to make your mod compatible with v50 ? I have not tested these forks, but it might be interesting to check them

**Comment by sfDesat** [comment]
LethalLevelLoader itself has a manual (install manually) beta currently. [This versions](https://thunderstore.io/c/lethal-company/p/Pineguys/LethalLevelLoaderFixedV50/) should work with Celestial Tint if you dont want to go through the effort of installing the LethalLevelLoader Beta.

I wont change the LethalLevelLoader version for now, because I know LethalLevelLoader Beta will eventually go into the release branch and get uploaded to the thunderstore

**Comment by LinkTroisUn** [comment]
I will try that.

Thanks
